services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - blog

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      WP_ENV: development
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
    networks:
      - blog
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - blog
    depends_on:
      - php

  wpcli:
    image: wordpress:cli-php8.3
    user: "33:33"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      WP_ENV: development
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080/wp
    networks:
      - blog
    depends_on:
      - db
    profiles:
      - cli
    command: tail -f /dev/null

volumes:
  db-data:

networks:
  blog:
    driver: bridge