# Production docker-compose.yml
# Used by GitHub Actions deployment workflow
# Variables are substituted using envsubst during deployment

services:
  ${PROJECT_NAME}-nginx:
    image: ${NGINX_IMAGE}
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=le"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
    volumes:
      - ${PROJECT_NAME}-uploads:/var/www/html/web/app/uploads
    networks:
      - ${PROJECT_NAME}
      - traefik
    depends_on:
      - ${PROJECT_NAME}-php

  ${PROJECT_NAME}-php:
    image: ${PHP_IMAGE}
    container_name: ${PROJECT_NAME}-php
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${PROJECT_NAME}-uploads:/var/www/html/web/app/uploads
      - /srv/backups/${PROJECT_NAME}:/backup
    networks:
      - ${PROJECT_NAME}
    depends_on:
      - ${PROJECT_NAME}-db

  ${PROJECT_NAME}-db:
    image: mariadb:10.11
    container_name: ${PROJECT_NAME}-db
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_TCP_PORT=3306
    command: --default-authentication-plugin=mysql_native_password --port=3306
    volumes:
      - ${PROJECT_NAME}-data:/var/lib/mysql
    networks:
      - ${PROJECT_NAME}

volumes:
  ${PROJECT_NAME}-data:
  ${PROJECT_NAME}-uploads:

networks:
  ${PROJECT_NAME}:
    driver: bridge
  traefik:
    external: true
